[package]
name = "rapid-note"
version = "0.1.0"
authors = ["Tomochika Hara <rust@thara.jp>"]

[dependencies]
error-chain = "0.12.0"
chrono = "0.4.5"
regex = "1"
shellexpand = "1.0"
toml = "0.4.6"
serde = "1.0.75"
serde_derive = "1.0.75"
clap = "2.32.0"
pad = "0.1"
strfmt = "0.1.6"
